version: "3"
services:
  postgres:
    image: postgres
    container_name: faithful_db_postgres
    environment:
      POSTGRES_DB: faithfulFiles_db_postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mongodb:
  #   image: mongo
  #   container_name: faithful_db_mongodb
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data:/data/db

volumes:
  postgres_data:
  # mongodb_data:
