version: "3"
services:
  app:
    container_name: bearerchat_app
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: bearer_db
    restart: always
    environment:
      POSTGRES_DB: bearerchat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
